# Generated by Django 3.2.4 on 2021-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_one', models.ImageField(upload_to='cars')),
                ('image_two', models.ImageField(upload_to='cars')),
                ('image_three', models.ImageField(upload_to='cars')),
                ('image_four', models.ImageField(upload_to='cars')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Lexus', 'Lexus'), ('Hyundai', 'Hyundai'), ('Renault', 'Renault'), ('BMW', 'BMW'), ('Any', 'Any')], default='Any', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Any', 'Any')], default='Any', max_length=100)),
                ('price', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
