# Generated by Django 3.2.4 on 2021-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='Any', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Lexus', 'Lexus'), ('Hyundai', 'Hyundai'), ('Renault', 'Renault'), ('BMW', 'BMW')], default='Any', max_length=100),
        ),
    ]
