# Generated by Django 3.2.4 on 2021-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20210713_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
