# Generated by Django 3.2.4 on 2021-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20210713_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Lexus', 'Lexus'), ('Hyundai', 'Hyundai'), ('Renault', 'Renault'), ('BMW', 'BMW')], max_length=100),
        ),
    ]
