# Generated by Django 3.2.4 on 2021-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20210713_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
