# Generated by Django 3.2.4 on 2021-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_car_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Beige', 'Beige'), ('Orange', 'Orange'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Purple', 'Purple')], max_length=50),
        ),
    ]
